
name: firebase_dart

repository: https://github.com/appsup-dart/firebase_dart


packages:
  - packages/**
ignore:
  - packages/**/example

ide:
  intellij: false

command:
  version:
    linkToCommits: true
    hooks: 
      pre:
        exec: dart test -j 1
        packageFilters:
          flutter: false
      preCommit:
        exec: "$PWD/remove-prereleases-from-changelog.sh"


 